version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    command: --max_allowed_packet=200M
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: corner
      MARIADB_USER: corner
      MARIADB_PASSWORD: corner
    ports:
      - 3306:3306
    # volumes:
    #   - ./docker-volume:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  # coturn:
  #   image: coturn/coturn
  #   restart: always
  #   ports:
  #     - 3478:3478
  #     - 3478:3478/udp
  #     - 5349:5349
  #     - 5349:5349/udp
  #     - 49160-49200:49160-49200/udp

# docker run -d -p 3478:3478 -p 3478:3478/udp -p 5349:5349 -p 5349:5349/udp -p 49160-49200:49160-49200/udp \
#        coturn/coturn -n --log-file=stdout \
#                         --external-ip='$(detect-external-ip)' \
#                         --min-port=49160 --max-port=49200