version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: corner
      MARIADB_USER: corner
      MARIADB_PASSWORD: corner
    ports:
      - 3306:3306
    # volumes:
    #   - ./docker-volume:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
